# Generated by Django 2.2 on 2020-03-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_doctor_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comment_count',
        ),
    ]
