# Generated by Django 2.2 on 2020-04-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200404_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='review',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='review',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='width_field',
        ),
        migrations.RemoveField(
            model_name='servicepicture',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='servicepicture',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Doctors/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ReviewsPic/'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ServiceCategory/'),
        ),
        migrations.AlterField(
            model_name='servicepicture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ServicePic/'),
        ),
    ]
